from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, Integer, JSON
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class InsightsCache(Base):
    """Cached AI spending insights for one account + month.

    Insights are generated by the Anthropic API, which is slow (~2-3s) and
    costs money per call, so we cache the result for 24 hours (see the router's
    freshness check) and reuse it instead of regenerating on every Dashboard load.
    One row per account/month/year.
    """

    __tablename__ = "insights_cache"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    account_id: Mapped[int] = mapped_column(
        ForeignKey("accounts.id"), nullable=False, index=True
    )
    month: Mapped[int] = mapped_column(Integer, nullable=False)
    year: Mapped[int] = mapped_column(Integer, nullable=False)
    # JSON array of {title, body, type, icon} insight objects.
    insights: Mapped[list] = mapped_column(JSON, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=lambda: datetime.now(timezone.utc)
    )
