import { useState, useEffect } from 'react'
import { getInsights } from '../api/client'

// Left-border + tint per insight type.
const TYPE_STYLES = {
  positive: 'border-l-emerald-400 bg-emerald-50/40',
  warning: 'border-l-amber-400 bg-amber-50/40',
  tip: 'border-l-blue-400 bg-blue-50/40',
  neutral: 'border-l-gray-300 bg-gray-50/60',
}

export default function AIInsights({ month, year }) {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [error, setError] = useState(false)

  function fetchInsights(refresh = false) {
    if (refresh) setRefreshing(true)
    else setLoading(true)
    setError(false)
    getInsights({ month, year, refresh })
      .then((res) => setData(res.data))
      .catch(() => setError(true))
      .finally(() => {
        setLoading(false)
        setRefreshing(false)
      })
  }

  useEffect(() => {
    fetchInsights(false)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [month, year])

  const insights = data?.insights || []
  const configured = data?.configured
  const busy = loading || refreshing

  return (
    <section className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 mb-6">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold flex items-center gap-2">
          <span className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 bg-clip-text text-transparent">
            BudgetBuddy AI
          </span>
          <span>✨</span>
        </h2>
        {configured && (
          <button
            type="button"
            onClick={() => fetchInsights(true)}
            disabled={busy}
            title="Generate fresh insights"
            aria-label="Refresh insights"
            className="inline-flex items-center gap-1.5 min-h-[36px] px-3 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-100 transition-colors disabled:opacity-50"
          >
            <svg
              className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Refresh
          </button>
        )}
      </div>

      {busy ? (
        <InsightsSkeleton />
      ) : error ? (
        <p className="text-sm text-gray-500">
          Couldn't load insights right now.{' '}
          <button type="button" onClick={() => fetchInsights(false)} className="text-emerald-600 font-medium hover:underline">
            Try again
          </button>
        </p>
      ) : !configured ? (
        <div className="rounded-lg bg-gradient-to-br from-indigo-50 to-pink-50 border border-indigo-100 p-6 text-center">
          <p className="text-2xl mb-1">✨</p>
          <p className="text-sm font-semibold text-gray-900">AI Insights coming soon!</p>
          <p className="text-sm text-gray-500 mt-0.5">
            Personalized analysis of your spending will appear here.
          </p>
        </div>
      ) : insights.length === 0 ? (
        <p className="text-sm text-gray-500">No insights for this month yet — add some transactions to get started.</p>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {insights.map((ins, i) => (
            <div
              key={i}
              className={`border border-gray-200 border-l-4 rounded-lg p-4 ${TYPE_STYLES[ins.type] || TYPE_STYLES.neutral}`}
            >
              <div className="flex items-start gap-2.5">
                <span className="text-xl leading-none shrink-0">{ins.icon}</span>
                <div className="min-w-0">
                  <p className="text-sm font-semibold text-gray-900">{ins.title}</p>
                  <p className="text-sm text-gray-600 mt-0.5">{ins.body}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {configured && data?.generated_at && !busy && (
        <p className="text-[11px] text-gray-400 mt-3">
          Generated by AI · {data.cached ? 'cached' : 'fresh'} · refreshes every 24h
        </p>
      )}
    </section>
  )
}

function InsightsSkeleton() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
      {[0, 1, 2, 3].map((i) => (
        <div key={i} className="border border-gray-200 border-l-4 border-l-gray-200 rounded-lg p-4 animate-pulse">
          <div className="flex items-start gap-2.5">
            <div className="w-5 h-5 rounded bg-gray-100 shrink-0" />
            <div className="flex-1 space-y-2">
              <div className="h-3.5 w-1/2 bg-gray-100 rounded" />
              <div className="h-3 w-full bg-gray-100 rounded" />
              <div className="h-3 w-3/4 bg-gray-100 rounded" />
            </div>
          </div>
        </div>
      ))}
    </div>
  )
}
