"""add recurring transactions

Revision ID: 349e24a2edfd
Revises: 31ba33e0e308
Create Date: 2026-05-27 20:36:35.969035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349e24a2edfd'
down_revision: Union[str, Sequence[str], None] = '31ba33e0e308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('paid_by', sa.Integer(), nullable=False),
    sa.Column('is_split', sa.Boolean(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transactions_id'), 'recurring_transactions', ['id'], unique=False)
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('recurring_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.create_foreign_key('fk_transactions_recurring_id', 'recurring_transactions', ['recurring_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.drop_constraint('fk_transactions_recurring_id', type_='foreignkey')
        batch_op.drop_column('recurring_id')
        batch_op.drop_column('is_recurring')
    op.drop_index(op.f('ix_recurring_transactions_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    # ### end Alembic commands ###
